<?php

/**
 * This is the model base class for the table "tbl_follow".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Follow".
 *
 * Columns in table "tbl_follow" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $user_follow
 * @property integer $user_followed
 * @property integer $created_at
 * @property integer $update_at
 * @property integer $active
 * @property string $type
 *
 */
abstract class BaseFollow extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_follow';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Follow|Follows', $n);
	}

	public static function representingColumn() {
		return 'type';
	}

	public function rules() {
		return array(
			array('user_follow, user_followed, created_at, update_at, active', 'numerical', 'integerOnly'=>true),
			array('type', 'length', 'max'=>255),
			array('user_follow, user_followed, created_at, update_at, active, type', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_follow, user_followed, created_at, update_at, active, type', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_follow' => Yii::t('app', 'User Follow'),
			'user_followed' => Yii::t('app', 'User Followed'),
			'created_at' => Yii::t('app', 'Created At'),
			'update_at' => Yii::t('app', 'Update At'),
			'active' => Yii::t('app', 'Active'),
			'type' => Yii::t('app', 'Type'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_follow', $this->user_follow);
		$criteria->compare('user_followed', $this->user_followed);
		$criteria->compare('created_at', $this->created_at);
		$criteria->compare('update_at', $this->update_at);
		$criteria->compare('active', $this->active);
		$criteria->compare('type', $this->type, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}